# config.yaml

cookie:
  name: franc                   # Nombre de la cookie
  key: your-secure-cookie-key   # Cadena secreta aleatoria
  expiry_days: 30               # Vence en 30 días

credentials:
  usernames:
    jsmith:
      first_name: John
      last_name: Smith
      email: jsmith@gmail.com
      password: abc             # Se hashea al inicializar
      roles:
        - admin
        - editor
        - viewer
    rbriggs:
      first_name: Rebecca
      last_name: Briggs
      email: rbriggs@gmail.com
      password: def
      roles:
        - viewer

oauth2:
  google:
    client_id: your-google-client-id
    client_secret: your-google-client-secret
    redirect_uri: https://your-app-url/.auth/google/callback
  microsoft:
    client_id: your-ms-client-id
    client_secret: your-ms-client-secret
    tenant_id: your-tenant-id
    redirect_uri: https://your-app-url/.auth/microsoft/callback

pre-authorized:
  emails:
    - melsby@gmail.com

api_key: your-stauthenticator-api-key
